### ISSUE TITLE
想请教几个问题

### ISSUE THREAD

**Issue by CanNian969** [0x3f3f3f3f/Satania-QQBot#14]
1. 运行程序步骤是什么，我先运行MCL并登录，然后node app.js，报错
opened!
D:\Html_Workspace\Satania-QQBot\libs\miraiApiHttp.js:43
        return res.data;
                   ^
TypeError: Cannot read properties of null (reading 'data')
    at Object.about (D:\Html_Workspace\Satania-QQBot\libs\miraiApiHttp.js:43:20)
    at async WebSocket.onOpen (D:\Html_Workspace\Satania-QQBot\app.js:102:45)

2. 运行node gfw_outside_service.js会报错，Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Html_Workspace\Satania-QQBot\node_modules\_pkg-dir@6.0.1@pkg-dir\index.js from D:\Html_Workspace\Satania-QQBot\node_modules\puppeteer\lib\cjs\puppeteer\initialize-node.js not supported.
Instead change the require of index.js in D:\Html_Workspace\Satania-QQBot\node_modules\puppeteer\lib\cjs\puppeteer\initialize-node.js to a dynamic import() which is available in all CommonJS modules.

如果大佬不限麻烦的话，可以加一下我qq：1025109710吗，有一些地方不懂但是找不到解决方法，可以有偿

**Comment by CHFreezer** [comment]
如果已经运行过npm install和pip install安装好相关依赖，请尝试下面运行时版本
这是我目前服务器上跑的版本：
mirai-console-2.9.0-M1.jar
mirai-console-terminal-2.9.0-M1.jar
mirai-core-all-2.9.0-M1.jar
mirai-api-http-v2.2.0.mirai.jar
node v16.5.0
我自己的qq机器人已经跑了大半年，mirai http plugin和node可能都有新版本，目前还没有精力去维护至最新版本，请见谅

**Comment by CanNian969** [comment]
谢谢大佬，果然是node版本问题
