### ISSUE TITLE
请问有数据库sql吗

### ISSUE THREAD

**Issue by Syuam** [0x3f3f3f3f/Satania-QQBot#2]
没有表结构跑不起来。。。

**Comment by KumoKyaku** [comment]
阿里云 rm-2zee126u825kkw48uvo.mysql.rds.aliyuncs.com    3306  user pvdb pw pvdb

**Comment by CHFreezer** [comment]
> 没有表结构跑不起来。。。

`node Pixiv_database.js [你需要爬的p站标签逗号分隔]`
来生成数据库
例如：
`node Pixiv_database.js レム(リゼロ),初音ミク,サターニャ,胡桃沢=サタニキア=マクドウェル,時崎狂三,イリヤ,ララフェル,Lalafell,拉拉菲尔 char`

**Comment by CHFreezer** [comment]
https://github.com/0x3f3f3f3f/Satania-QQBot/blob/d838b448b3a31141a7d84a4f11ee74fd1ed4ccca/protocols/PixivPic.js#L179
你需要自己补全inside_tags里面的标签，type分sex、char，完成以后，脚本每天中午十二点会按照inside_tags里的标签自动爬取数据库
