### ISSUE TITLE
请问还能用吗

### ISSUE THREAD

**Issue by jjsisjjz** [0x3f3f3f3f/Satania-QQBot#6]
作者，这个还能用吗

**Comment by CHFreezer** [comment]
QQLight自己炸了，目前没有宿主用不了

**Comment by CHFreezer** [comment]
已经迁移兼容至Mirai，不过未做测试

**Comment by IrisYagami** [comment]
所以这个是还在运营咩？

**Comment by CHFreezer** [comment]
> 所以这个是还在运营咩？

大部分还是能跑，就是pixiv api最近加了人机验证码，js部分我还在想办法

**Comment by CHFreezer** [comment]
pixiv api改成[pixivpy](https://github.com/upbit/pixivpy)
